### ISSUE TITLE
[Bug]: Cannot load plugin in Copilot

### ISSUE THREAD

**Issue by Balabalavatasky** [OfficeDev/Copilot-for-M365-Plugins-Samples#39]
### Sample

msgext-northwind-inventory-ts

### Description

I tried with the lab of **Building Message Extensions for Microsoft Copilot for Microsoft 365**. However, when it comes to Exercise 3, I cannot load plugin in Copilot.

### Steps to reproduce

1. Set up your development environment.

3. Sideloading is enabled.
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/12893064/bcc29189-d257-44ee-9be6-60068f4985cc)

4. Bot is successfully added.
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/12893064/f7f38f77-c9b6-4bb2-beb9-d7e22cdc565c)

5. Doing well with bot. 
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/12893064/d36da073-0eb4-4ace-9dc3-ac1ab5e2a8b0)

6. Tried with Copilot - Failed. 
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/12893064/d1369ac9-aefd-4f43-91f3-935b4c3312d2)

### Expected results

 (What suggests in the lab)

![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/12893064/6f7a1440-9de1-4ca4-bc8d-8cf60006eb9a)

### Actual results

In my practices:
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/12893064/d1369ac9-aefd-4f43-91f3-935b4c3312d2)

**Comment by garrytrinder** [comment]
Thanks for reporting @Balabalavatasky, apologies for the trouble. As this is an issue on the Copilot side rather than the sample itself, we will need to route this to the appropriate team internally. Leave this with me.

**Comment by garrytrinder** [comment]
Copilot of Microsoft 365 extensibility is currently in private preview. Please refer to the [requirements for Plugin development](https://learn.microsoft.com/microsoft-365-copilot/extensibility/prerequisites#requirements-for-plugin-development) section in MS Learn to enable Copilot for extensibility in your tenant.

**Comment by garrytrinder** [comment]
Closing issue as not related to the sample.

Please raise a [support ticket](https://learn.microsoft.com/microsoft-365/admin/get-help-support) from the Microsoft 365 Admin Center for further assistance.
