### ISSUE TITLE
Sample is not working in Teams Copilot (M365 Chat) but working in Message Extension from chat

### ISSUE THREAD

**Issue by ChetanSharma-msft** [OfficeDev/Copilot-for-M365-Plugins-Samples#41]
### Sample

[msgext-multiparam-ts](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/tree/main/samples/msgext-multiparam-ts)

### Description

I am able to run the sample locally and ME is working from chat and able to debug the code.
App is not working in M365 chat even after enabling the plugin.

https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/tree/main/samples/msgext-multiparam-ts

### Steps to reproduce

Setup the sample locally.
Search the prompt in Teams Copilot (M365 Chat) 
Debugging is not coming here:

![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/59052547/a8086c90-e4a0-4931-9dff-5558ae4b3bee)

### Expected results

Should get the response in M365 Chat

### Actual results

It is not searching the prompts in the actual application.

**Comment by garrytrinder** [comment]
@ChetanSharma-msft have you tried the message extension in Outlook? 

Copilot and Outlook use the same bot channel, Microsoft 365. If the message extension is not working in Outlook then check the configuration of the bot in the dev.botframework.com portal, it should look like this.

![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/11563347/a0a98f7f-6179-49ef-a9ec-7c7a9f32e384)

I have seen in the past where the Microsoft 365 channel is not configured on the bot but the plugin is displayed in Copilot, like what you are seeing.

**Comment by garrytrinder** [comment]
I just pushed an update to make the the query parameter retrieval code more robust.

**Comment by garrytrinder** [comment]
@ChetanSharma-msft are you still facing issues?
