### ISSUE TITLE
[Bug]: not showing up as a copilot plugin

### ISSUE THREAD

**Issue by PhilippTP** [OfficeDev/Copilot-for-M365-Plugins-Samples#49]
### Sample

msgext-doc-search-js

### Description

The Message Extension worked fine, but it is not working as a copilot pugin. It is not showing up there. 

### Steps to reproduce

debugging the app localy

### Expected results

showing up in the plugins in M365 Chat

### Actual results

Not showing up

**Comment by garrytrinder** [comment]
If the plugin does not appear in the flyout but can be used in Teams and Outlook then it suggests an issue with the tenant configuration. Please raise a support ticket for this to be looked into, see https://learn.microsoft.com/en-gb/microsoft-365-copilot/extensibility/prerequisites#requirements-for-plugin-development.
