### ISSUE TITLE
Issue: while setting up basic install on vscode teams toolkit

### ISSUE THREAD

**Issue by amitlals** [OfficeDev/Copilot-for-M365-Plugins-Samples#67]
### Sample

msgext-doc-search-js

### Description

There are lots of issue on enterprise E5 connectivity issues, required elaborated steps with details. 

![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/37605691/3acec8fa-ee5a-45aa-9867-c82b576caff6)

### Steps to reproduce

na

### Expected results

connectivity 

### Actual results

na

**Comment by garrytrinder** [comment]
Hey @amitlals 

It looks like you Microsoft 365 tenant doesn't have sideloading enabled. Follow the below guide to enable custom apps in the Microsoft Teams Admin Center. Note that it can take 24 hours for this to become active.

https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites#prepare-a-developer-tenant-for-testing

**Comment by amitlals** [comment]
Thank you for the update. I am look into it.

Regarding the process for FTEs to access Microsoft 365 Copilot, I am seeking clarification. As we are not enrolled in TAP and rely on devbox, I'm uncertain of the steps involved. I attempted to use a CDX E5 license, but authorization was unsuccessful. Could this be due to its status as a private preview? pls suggest

**Comment by garrytrinder** [comment]
You will need access to a Microsoft 365 tenant with Copilot enabled. AFAIK it's not possible to activate Copilot in a CDX tenant.

Extending Copilot for Microsoft 365 with plugins is currently opt-in, see [Requirements for plugin development](https://learn.microsoft.com/microsoft-365-copilot/extensibility/prerequisites#requirements-for-plugin-development) for more detail.
