### ISSUE TITLE
[Bug]: Not showing up as a copilot plugin

### ISSUE THREAD

**Issue by Piyush-Use-Personal** [OfficeDev/Copilot-for-M365-Plugins-Samples#80]
### Sample

msgext-northwind-inventory-ts

### Description

The Message Extension worked fine, but it is not working as a copilot plugin. It is not showing up there.
Similar to: https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/issues/49

I have also checked on https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/build-bot-based-plugin?tabs=visual-studio-code but same result on performing exactly same steps

### Steps to reproduce

debugging the app locally

### Expected results

Showing up in the plugins in M365 Chat

### Actual results

Not showing up

### Additional Info

I can provide this information on a run basis if required

**Comment by rabwill** [comment]
Hi @Piyush-Use-Personal thanks for reporting. Are you able to run the ME in Outlook as well? 
Is the plugin showing up in the M365 Chat plugin enable/disable list?

**Comment by adepalmaRepl** [comment]
Hi @rabwill  I too have the same problem

**Comment by garrytrinder** [comment]
@Piyush-Use-Personal plugin development is currently in private preview which requires a support ticket to be raised. If you have done this and plugins are still not showing, please raise another support ticket.

> During the public preview of plugins, customers who are licensed for Copilot in production will need an administrator to enable their tenant for the preview by submitting a support ticket using the sentence "enable plugins for Copilot for Microsoft 365" within the ticket, or making a request to their Microsoft Customer Success Account Manager.
