### ISSUE TITLE
[Bug]: 'Documents' folder is not available

### ISSUE THREAD

**Issue by Prasad-MSFT** [OfficeDev/Copilot-for-M365-Plugins-Samples#84]
### Sample

msgext-doc-search-csharp

### Description

In [this](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/tree/main/samples/msgext-doc-search-csharp#step-1---upload-documents-to-azure-ai-search) step it is mentioned that "Drag and drop the files from the [documents](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/blob/main/samples/msgext-doc-search-csharp/documents) folder to the Upload files section". However, the files folder is nowhere to be found.

### Steps to reproduce

Click on **documents** hyperlink, you will get below mentioned error:
Drag and drop the files from the [documents](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/blob/main/samples/msgext-doc-search-csharp/documents) folder to the Upload files section, then select Upload files.

![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/62237649/75a8d4c0-8121-4182-aca3-b559e9f4f1d5)

### Expected results

The folder should be available.

### Actual results

![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/62237649/75a8d4c0-8121-4182-aca3-b559e9f4f1d5)

**Comment by garrytrinder** [comment]
Thanks for letting us know @Prasad-MSFT and apologies for the trouble. The documents folder has now been added.
