### ISSUE TITLE
[Bug]: 'Prepare Teams apps dependencies' step fails with error "Credential lifetime exceeds the max value allowed as per assigned policy '538f1913-366a-440a-95a0-e195cb55b282"

### ISSUE THREAD

**Issue by Prasad-MSFT** [OfficeDev/Copilot-for-M365-Plugins-Samples#85]
### Sample

msgext-multiparam-csharp

### Description

While setting up this sample ([Copilot-for-M365-Plugins-Samples/samples/msgext-multiparam-csharp at main · OfficeDev/Copilot-for-M365-Plugins-Samples (github.com)](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/tree/main/samples/msgext-multiparam-csharp)), we came across below error while trying to Run [Prepare Teams apps dependencies](https://learn.microsoft.com/microsoftteams/platform/toolkit/toolkit-v4/debug-local-vs?pivots=visual-studio-v17-7#set-up-your-teams-toolkit)
 
 
**Error Details:**
{"error":{"code":"CredentialInvalidLifetimeAsPerAppPolicy","message":"Credential lifetime exceeds the max value allowed as per assigned policy '538f1913-366a-440a-95a0-e195cb55b282'.","details":[{"code":"InvalidKeyEndDate","message":"Credential lifetime exceeds the max value allowed as per assigned policy '538f1913-366a-440a-95a0-e195cb55b282'."

### Steps to reproduce

Right-click on your project.

Select Teams Toolkit > Prepare Teams App Dependencies.
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/62237649/21385a15-91a1-4e5c-86a0-b7cfd0b3c733)

Your Microsoft 365 account needs to have the custom app upload permission before you sign in. Ensure that your Teams app can be uploaded to the tenant, otherwise your Teams app can fail to run in Teams Client.

Sign in to your Microsoft 365 Account and then select Continue.

![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/62237649/96e6464b-3adc-4a9e-ac8b-c48c3fe8a6eb)

### Expected results

This step should get completed successfully and we should be able to 'Start Debugging'

### Actual results

Failed to Execute lifecycle provision due to failed action: botAadApp/create. HttpClientError:A http client error happened while performing the botAadApp/create task. The error response is: {"error":{"code":"CredentialInvalidLifetimeAsPerAppPolicy","message":"Credential lifetime exceeds the max value allowed as per assigned policy '538f1913-366a-440a-95a0-e195cb55b282'.","details":[{"code":"InvalidKeyEndDate","message":"Credential lifetime exceeds the max value allowed as per assigned policy '538f1913-366a-...

**Comment by garrytrinder** [comment]
Sorry for the trouble @Prasad-MSFT 

This seems like it's an issue in Teams Toolkit than the sample itself.

**Comment by blackchoey** [comment]
Hi @Prasad-MSFT a recent policy change inside Microsoft tenant resulted in this error. Please follow the workaround in https://github.com/OfficeDev/TeamsFx/issues/10905 to mitigate this issue.
