### ISSUE TITLE
[Bug]: Intermittent 500 Error when running Northwind Sample

### ISSUE THREAD

**Issue by francogior** [OfficeDev/Copilot-for-M365-Plugins-Samples#89]
### Sample

msgext-northwind-inventory-ts

### Description

We are experiencing intermittent issues when running the Northwind sample in Teams Toolkit, which results in a 500 error. This behavior is observed across both Teams Classic and the new Teams. The issue was not present last week.

### Steps to reproduce

1. Clone repo
2. Setup Northwind sample (database and duplicate `.env.local.user.sample`)
3. Message Extension works OK when using it directly/standalone:
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/115115543/8737271c-bbe0-4458-9b40-3a7e9f31cb05)
4. Enable Northwind plugin in Copilot and developer mode. Ask a question but receive an error instead:
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/115115543/b7253995-88a1-4071-8e4b-9bffa7af63c9)

### Expected results

Copilot should contact our localhost server and return and answer, as shown in the sample images:
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/115115543/c703ee25-0707-4b51-85ba-4cb712bccb66)

### Actual results

Error described above:
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/115115543/b7253995-88a1-4071-8e4b-9bffa7af63c9)

### Additional Info

- Our localhost Teams server does not produce any new logs, indicating that the bot is not contacted at all and may be something config related. If not, could it be a temporary Copilot/M365 outage?
- We were developing a plugin but hit this issue this week, so we are certain that we can sideload plugins in Copilot (we submitted a ticket for the private preview last week and worked OK)

**Comment by luismanez** [comment]
Having exactly this same issue, but in our case with sample: [msgext-doc-search-csharp](https://adoption.microsoft.com/en-us/sample-solution-gallery/sample/officedev-copilot-for-m365-plugins-samples-msgext-doc-search-csharp/)
IMO seems like an issue with the tunnelling thing. Copilot apparently makes the call, but is lost "in the space"...

Thing is that the npm finder sample that is created from Teams toolkit for VS Code, works fine.

BTW, same behavior tested in 2 different Tenants, our prod tenant, and the shared MVP tenant provided by MS.

Any clue @garrytrinder @aycabas ?

Thanks!

**Comment by luismanez** [comment]
As weird as it seems, I've created a new Teams project using Visual Studio and Teams toolkit. I chose the "Custom Search Results" template. As mentioned before, that worked fine even in Copilot. Then, I've updated the project with code from the sample [msgext-doc-search-csharp](https://adoption.microsoft.com/en-us/sample-solution-gallery/sample/officedev-copilot-for-m365-plugins-samples-msgext-doc-search-csharp/), and this is working fine too, and is being called from Copilot...

The only different I see are the nuget packages versions (but I updated sample versions and was failing too), and the other difference is that my new project is using .NET 8, and sample is still .NET 6 (haven´t tried the upgrade).

**Comment by garrytrinder** [comment]
@francogior @luismanez this could be related to an intermittent outage. 

From the debug logs it would appear that Copilot was able to discover the plugin and select the correct command to execute. I'm going to assume that no breakpoints were hit in the plugin code, so no response was able to be returned by the plugin as it never received the request.

Is this still an issue?

**Comment by francogior** [comment]
@garrytrinder Hi! thanks for the response. Regarding your points:

> I'm going to assume that no breakpoints were hit in the plugin code, so no response was able to be returned by the plugin as it never received the request.
Exactly, I've added more logs to the HTTP server and no endpoints were contacted at all.

> Is this still an issue?
It was an issue up until last Friday (three days ago), but I'll double-check today just in case.

Thanks!

**Comment by francogior** [comment]
@garrytrinder Hey Garry, just wanted to let you know that the issue seems to be present still. Interestingly, the sample sometimes works, but eventually fails when stopping and restarting the browser/server/VSCode.

Given that we've seen this behavior during the last week (and before), could this be something different from a "temporal" outage? I'm attaching below a screenshot from today, showing the same issue (no logs in the console):
![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/115115543/940d3cba-8e2b-4cdd-89aa-705187ed0249)



Thanks!

**Comment by garrytrinder** [comment]
@francogior I just tested this sample against the tenant that I have access to using your prompt and all is working fine.

![image](https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/assets/11563347/54c633df-ef8d-482e-a2d0-1b0b674cda8c)

Could you raise a support ticket in the Admin portal and reference this issue?
